"""Added caption field for Venue and Show

Revision ID: 2f24ca29de28
Revises: e8c2dd271097
Create Date: 2023-03-18 21:31:45.115573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f24ca29de28'
down_revision = 'e8c2dd271097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=128), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('caption')

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
