"""empty message

Revision ID: 57ed5228dece
Revises: bde43e4ae3d5
Create Date: 2023-03-22 20:34:44.347444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ed5228dece'
down_revision = 'bde43e4ae3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint('u_venue_name_loc', ['name', 'location'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_constraint('u_venue_name_loc', type_='unique')

    # ### end Alembic commands ###
