"""empty message

Revision ID: bde43e4ae3d5
Revises: 2549be40ae70
Create Date: 2023-03-21 23:10:54.131902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde43e4ae3d5'
down_revision = '2549be40ae70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_venue',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'venue_id')
    )
    op.drop_table('show__venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show__venue',
    sa.Column('show_id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.Column('sold', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('show_id', 'venue_id')
    )
    op.drop_table('show_venue')
    # ### end Alembic commands ###
